"""Add title to tickets

Revision ID: 328abad5f6d4
Revises: 6af4f08c8ae7
Create Date: 2025-04-28 08:10:38.299669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '328abad5f6d4'
down_revision: Union[str, None] = '6af4f08c8ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.drop_constraint('chat_messages_user_id_fkey', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'users', ['user_id'], ['id'])
    op.add_column('tickets', sa.Column('title', sa.String(length=255), nullable=False))
    op.alter_column('tickets', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.drop_constraint('tickets_owner_id_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_owner_id_fkey', 'tickets', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.alter_column('tickets', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tickets', 'title')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('chat_messages_user_id_fkey', 'chat_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    # ### end Alembic commands ###
